import { StyleSheet } from "react-native";
import colors from "../../styles/colors";

export default StyleSheet.create({
    container: {
        alignItems: 'center',
        backgroundColor: colors.background,
        flex: 1,
        justifyContent: 'flex-start',
        padding: 20,
    },
    title: {
        color: colors.text_basic,
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 20,
    },
    textSelectContainer: {
        color: colors.primary,
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 15,
        marginBottom: 20,
    },
    selectContainer: {
        width: '100%',
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    picker: {
        width: '80%',
        color: colors.text_basic,
        borderWidth: 2,
        borderRadius: 5,
        borderColor: colors.border,
        overflow: "hidden",
        backgroundColor: colors.white,
        marginBottom: 60,
    },
    container_table: {
        marginLeft: 35,
        marginRight: 35,
        marginBottom: 20,
        alignItems: 'flex-start',
        backgroundColor: colors.background,
        flex: 1,
        justifyContent: 'flex-start',
    },
    table: {
        alignItems: 'flex-start',
        backgroundColor: colors.background,
        flex: 1,
        justifyContent: 'flex-start',
        flexDirection: 'row',
    },
    table_row: {
        borderTopWidth: 2,
        borderColor: colors.text_basic,
        borderRadius: 2,
    },
    table_header: {
        textAlign: 'center',
        color: colors.white,
        backgroundColor: colors.primary,
        fontSize: 10,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.text_basic,
        width: 80,
        height: 20,
    },
    table_text: {
        textAlign: 'center',
        color: colors.text_basic,
        fontSize: 10,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.text_basic,
        width: 80,
        height: 90,
    },
    table_actions: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.text_basic,
        width: 80,
        height: 90,
    },
    table_button: {
        marginRight: 3,
    },
    button_text: {
        textAlign: 'center',
        fontSize: 30,
    },
    switchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        marginTop: 5,
        marginBottom: 30,
    },
    text: {
        color: colors.text_basic,
        fontSize: 18,
        fontWeight: 'bold',
    },
})