import { StyleSheet } from "react-native";
import colors from "../../../styles/colors";

export default StyleSheet.create({
    container: {
        alignItems: 'flex-start',
        backgroundColor: colors.background,
        flex: 1,
        justifyContent: 'flex-start',
    },
    container_title: {
        alignItems: 'center',
        backgroundColor: colors.background,
        justifyContent: 'center',
        width: '100%',
        marginTop: 20,
        marginBottom: 20,
    },
    title: {
        color: colors.text_basic,
        fontSize: 25,
        fontWeight: 'bold',
    },
    container_search: {
        alignItems: 'center',
        backgroundColor: colors.background,
        justifyContent: 'center',
        width: '100%',
        marginTop: 10,
        marginBottom: 20,
    },
    textInput: {
        backgroundColor: colors.white,
        borderColor: colors.border,
        borderRadius: 5,
        borderWidth: 1,
        height: 40,
        marginBottom: 15,
        marginTop: 20,
        paddingHorizontal: 10,
        width: '80%',
        color: colors.text_basic,
    },
    container_table: {
        marginLeft: 20,
        marginRight: 20,
        marginBottom: 20,
        alignItems: 'flex-start',
        backgroundColor: colors.background,
        flex: 1,
        justifyContent: 'flex-start',
    },
    table: {
        alignItems: 'flex-start',
        backgroundColor: colors.background,
        flex: 1,
        justifyContent: 'flex-start',
        flexDirection: 'row',
    },
    table_row: {
        borderTopWidth: 2,
        borderColor: colors.text_basic,
        borderRadius: 2,
    },
    table_header_large: {
        textAlign: 'center',
        color: colors.white,
        backgroundColor: colors.primary,
        fontSize: 10,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.text_basic,
        width: 280,
        height: 30,
    },
    table_header: {
        textAlign: 'center',
        color: colors.white,
        backgroundColor: colors.primary,
        fontSize: 10,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.text_basic,
        width: 100,
        height: 30,
    },
    table_text_large: {
        textAlignVertical: 'center',
        textAlign: 'center',
        color: colors.text_basic,
        fontSize: 10,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.text_basic,
        width: 280,
        height: 30,
    },
    table_text: {
        textAlignVertical: 'center',
        textAlign: 'center',
        color: colors.text_basic,
        fontSize: 10,
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.text_basic,
        width: 100,
        height: 30,
    },
    table_actions: {
        flexDirection: 'row',
        borderLeftWidth: 1,
        borderRightWidth: 1,
        borderBottomWidth: 1,
        borderColor: colors.text_basic,
        width: 100,
        height: 30,
    },
    table_button: {
        marginRight: 3,
    },
    button_text: {
        textAlign: 'center',
        fontSize: 22,
    }
})